[aoai]
endpoint = "https://gnlzlxhi3u2qm-openai.openai.azure.com/"
key = "6cb4da2e40fc4fc8ac3eb1a3a2ce7e10"
deployment_name = "gpt-4o"
embedding_deployment_name = "text-embedding-ada-002"

[search]
endpoint = "https://gnlzlxhi3u2qm-search.search.windows.net"
key = "Bg948aGKks6dJ5RvwxUiRSoXo25jsTO5BRvFhSg6MwAzSeBQsTcp"
index_name = "contoso-suites-faq"

[speech]
key = "e107043225984db4a48b217b8d37b1c1"
region = "eastus2"

[language]
endpoint = "https://gnlzlxhi3u2qm-lang.cognitiveservices.azure.com/"
key = "a0c06b5f9d5a4eb1851cafa41d2c195e"

[api]
endpoint = "http://gnlzlxhi3u2qm-api.azurewebsites.net"

[cosmos]
endpoint = "https://gnlzlxhi3u2qm-cosmosdb.documents.azure.com:443/"
key = "IT3D5wwPyX8JrThiqtviPn44NQAX7wRKuEVOQtWcMW17JtzS4l97nSU72WtkaZtTMsO0Ao7laoTaACDbFUE9RA=="
database_name = "ContosoSuites"